version: '3.8'

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-8000}:8000"
    env_file:   # This points to the .env file in your project
      - ./django_api_financial/.env
    environment:
      - DJANGO_SETTINGS_MODULE=django_api_financial.settings
      - PORT=8200
    volumes:
      - .:/app
#    command: python django_api_financial/manage.py runserver 127.0.0.1:8000
    command: gunicorn django_api_financial.wsgi:application --bind 0.0.0.0:8000 --workers 1 --threads 1 --timeout 120