# Generated by Django 5.1.2 on 2024-10-17 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockTimeline',
            fields=[
                ('st_id', models.AutoField(primary_key=True, serialize=False)),
                ('st_day', models.DateField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockData',
            fields=[
                ('sd_id', models.AutoField(primary_key=True, serialize=False)),
                ('sd_open_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('sd_close_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('sd_high_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('sd_low_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('sd_volume', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('sd_price_prediction', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=30, null=True)),
                ('sd_symbol', models.CharField(max_length=8)),
                ('st_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_financial.stocktimeline')),
            ],
        ),
    ]
